// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: proto/borrowing.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BorrowingHandler_Borrow_FullMethodName = "/grpc.BorrowingHandler/Borrow"
	BorrowingHandler_Return_FullMethodName = "/grpc.BorrowingHandler/Return"
)

// BorrowingHandlerClient is the client API for BorrowingHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorrowingHandlerClient interface {
	Borrow(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Return(ctx context.Context, in *ReturnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type borrowingHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowingHandlerClient(cc grpc.ClientConnInterface) BorrowingHandlerClient {
	return &borrowingHandlerClient{cc}
}

func (c *borrowingHandlerClient) Borrow(ctx context.Context, in *BorrowRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BorrowingHandler_Borrow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingHandlerClient) Return(ctx context.Context, in *ReturnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BorrowingHandler_Return_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowingHandlerServer is the server API for BorrowingHandler service.
// All implementations must embed UnimplementedBorrowingHandlerServer
// for forward compatibility.
type BorrowingHandlerServer interface {
	Borrow(context.Context, *BorrowRequest) (*emptypb.Empty, error)
	Return(context.Context, *ReturnRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedBorrowingHandlerServer()
}

// UnimplementedBorrowingHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBorrowingHandlerServer struct{}

func (UnimplementedBorrowingHandlerServer) Borrow(context.Context, *BorrowRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Borrow not implemented")
}
func (UnimplementedBorrowingHandlerServer) Return(context.Context, *ReturnRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Return not implemented")
}
func (UnimplementedBorrowingHandlerServer) mustEmbedUnimplementedBorrowingHandlerServer() {}
func (UnimplementedBorrowingHandlerServer) testEmbeddedByValue()                          {}

// UnsafeBorrowingHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorrowingHandlerServer will
// result in compilation errors.
type UnsafeBorrowingHandlerServer interface {
	mustEmbedUnimplementedBorrowingHandlerServer()
}

func RegisterBorrowingHandlerServer(s grpc.ServiceRegistrar, srv BorrowingHandlerServer) {
	// If the following call pancis, it indicates UnimplementedBorrowingHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BorrowingHandler_ServiceDesc, srv)
}

func _BorrowingHandler_Borrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingHandlerServer).Borrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingHandler_Borrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingHandlerServer).Borrow(ctx, req.(*BorrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingHandler_Return_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingHandlerServer).Return(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingHandler_Return_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingHandlerServer).Return(ctx, req.(*ReturnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BorrowingHandler_ServiceDesc is the grpc.ServiceDesc for BorrowingHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BorrowingHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BorrowingHandler",
	HandlerType: (*BorrowingHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Borrow",
			Handler:    _BorrowingHandler_Borrow_Handler,
		},
		{
			MethodName: "Return",
			Handler:    _BorrowingHandler_Return_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/borrowing.proto",
}
